name: Go Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run golang test
        run: go test -v ./... -coverprofile ./coverage.out

      - name: Coverage check
        run: |
          echo "Quality Gate: checking test coverage is above threshold"
          totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
          echo "Threshold: ${{ vars.TEST_COVERAGE_THRESHOLD }}"
          echo "Current total coverage: $totalCoverage %"
          if (($(echo "$totalCoverage ${{ vars.TEST_COVERAGE_THRESHOLD }}" | awk '{print ($1 >= $2)}') )); then
            echo 'Passed'
          else
            echo "Current test coverage is below threshold. Please add more unit tests."
            echo "Fail"
            exit 1
          fi



